package com.heliommsfilho.quarkusdynamo.document;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

@DynamoDbBean
@Getter
@Setter
@ToString
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Customer {

    @EqualsAndHashCode.Include
    private String customerId;
    private String name;
    private String driverLicense;
    private Address homeAddress;
    private Address workAddress;
    private List<Vehicle> vehicles = new ArrayList<>();
    private Instant createTimestamp;
    private Instant updateTimestamp;

    @DynamoDbPartitionKey
    public String getCustomerId() { return customerId; }

    @DynamoDbAutoGeneratedTimestampAttribute
    public Instant getUpdateTimestamp() { return updateTimestamp; }

    @DynamoDbBean
    @Getter
    @Setter
    @ToString
    public static class Address {

        private String country;
        private String state;
        private String city;
        private String postalCode;
        private String addressLine1;
        private String addressLine2;
        private Instant createTimestamp;
        private Instant updateTimestamp;

        @DynamoDbAutoGeneratedTimestampAttribute
        public Instant getUpdateTimestamp() { return updateTimestamp; }
    }

    @DynamoDbBean
    @Getter
    @Setter
    @ToString
    @EqualsAndHashCode(onlyExplicitlyIncluded = true)
    public static class Vehicle {

        @EqualsAndHashCode.Include
        private String licensePlate;
        private String brand;
        private String model;
        private Integer year;
        private String color;
        private Instant createTimestamp;
        private Instant updateTimestamp;

        @DynamoDbAutoGeneratedTimestampAttribute
        public Instant getUpdateTimestamp() { return updateTimestamp; }
    }
}
